services:

  kafka:
    image: apache/kafka:latest
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
    ports:
      - '9092:9092'

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:6
    ports:
      - '6379:6379'

  api-gateway:
    build: ./services/api-gateway
    ports:
      - '3000:3000'
    depends_on:
      - auth-service
      - itinerary-service

  auth-service:
    build: ./services/auth-service
    ports:
      - '3001:3001'

  itinerary-service:
    build: ./services/itinerary-service
    ports:
      - '3002:3002'

  event-ingestion-service:
    build: ./services/event-ingestion-service
    ports:
      - '3003:3003'
    depends_on:
      rabbitmq:
        condition: service_healthy

  alert-processing-service:
    build: ./services/alert-processing-service
    depends_on:
      rabbitmq:
        condition: service_healthy
      kafka:
        condition: service_started
      itinerary-service:
        condition: service_started

  notification-service:
    build: ./services/notification-service
    ports:
      - '3004:3004'
    depends_on:
      - redis

  analytics-faas:
    build: ./services/analytics-faas
    ports:
      - '3005:3005'

  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-gateway
      - notification-service

  frontend-shell:
    image: nginx:latest
    volumes:
      - ./frontend/shell-app:/usr/share/nginx/html:ro
    ports:
      - '8081:80'

  frontend-itinerary:
    image: nginx:latest
    volumes:
      - ./frontend/itinerary-mf:/usr/share/nginx/html:ro
      - ./frontend/itinerary-mf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '8082:80'
    depends_on:
      - nginx

  frontend-alerts:
    image: nginx:latest
    volumes:
      - ./frontend/alerts-mf:/usr/share/nginx/html:ro
      - ./frontend/alerts-mf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '8083:80'
    depends_on:
      - nginx

networks:
  default:
    driver: bridge
